#!/bin/sh
set -e

# setup the git remote
git remote add upstream git@github.com:gganeshan/terraform-play.git
git fetch upstream

# which files changed in this PR?
git diff --name-only --diff-filter=ACMRTUXB upstream/master..HEAD | grep -i 'aws/projects/' | tee changed_files

# show modified files
cat changed_files

# which dirs changed in this PR?
 cut -f 1-3 -d '/' changed_files | sort -u | tee dirs

# show modified directories
cat dirs
