#!/bin/sh
set -e

# Loop through the modified dirs and run terraform commands
while read dir; do
  pushd ${dir}
  terraform remote config -backend=s3 -backend-config="bucket=2016-gg-dev" -backend-config="key=tfstate-${dir}/terraform.tfstate" -state="tfstate-${dir}/terraform.tfstate"
  terraform get
  terraform plan -module-depth=3
  popd
done < dirs
